// File generated by FlutterFire configuration for Notify Jobs.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// `dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// `
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4HKLllBma7SsHBeumtit83h9L9Z5eOzE',
    appId: '1:885309400735:android:bfc8050d6eeb1fef22e4aa',
    messagingSenderId: '885309400735',
    projectId: 'notify-jobs-753b8',
    databaseURL: 'https://notify-jobs-753b8-default-rtdb.firebaseio.com',
    storageBucket: 'notify-jobs-753b8.firebasestorage.app',
  );
}
